### ISSUE TITLE
Process dies with SIGSEGV

### ISSUE THREAD

**Issue by asbjornenge** [mattdesl/budo-chrome#5]
Whenever I have the remote debugging enabled on a chrome instance, the budo-chrome process segfaults :confused: 

```
fish: Process 30785, “budo-chrome” from job 1, “budo-chrome app/app.js --transform babelify | garnish” terminated by signal SIGSEGV (Address boundary error)
```

The Chrome instance seems unaffected.

```
Linux 3.17.4
Google Chrome 42.0.2311.90
Google Chrome 42.0.2311.82 beta
budo-chrome@2.0.0
watchify@3.1.1
```

Anything I can try? Would love to get this working :+1: :rocket:

**Comment by mattdesl** [comment]
Hmm, what version of Node are you running? `node -v`

Can you try quitting Chrome and then running with the `--open` command to let me know if that behaves any differently?

``` sh
budo-chrome app/app.js --open --transform babelify | garnish
```

Maybe @caspervonb has seen this before?

**Comment by caspervonb** [comment]
Never seen it segfault, does `ws` build with native modules in this case?

**Comment by asbjornenge** [comment]
@mattdesl I was running 0.12.0... upgraded to 0.12.2 and the segfaulting stopped :grin: Also tried io 1.7.1; no segfaulting :tada: 

I'm still having some trouble getting the hot reloading to work, but I'll open another issue if I can't figure it out. Thanks :+1:

**Comment by mattdesl** [comment]
Hmm strange! I will add it as a note to the docs.

Also be sure to read through the gotchas:
https://github.com/mattdesl/budo-chrome/tree/master/docs#drawbacks
