### ISSUE TITLE
How does this differ from LiveReactLoad?

### ISSUE THREAD

**Issue by gmaclennan** [mattdesl/budo-chrome#6]
Can this be used with React components? Or do we need LiveReactLoad for that?

**Comment by mattdesl** [comment]
This is a general-purpose live reload with a similar mechanism as [amok](https://github.com/caspervonb/amok). It uses V8's LiveEdit under the hood, through Chrome Remote Debugging protocol.

However, if you want to reload React components, you should probably stick to LiveReactLoad or react-hot-loader (webpack) which are both better suited for production use. budo-chrome is unfortunately pretty experimental and not really usable until some issues with V8 are resolved. :smile:

**Comment by gmaclennan** [comment]
Thank you, that is very clear.
